export default Object.freeze({
  Function: `Function`,
  Array: `Array`,
  Date: `Date`,
  Object: `Object`,
  plainObject: `Plain Object`,
  String: `String`,
  Number: `Number`,
  Boolean: `Boolean`,
  RegExp: `RegExp`,
  Undefined: `Undefined`,
  Null: `null`,
  Nil: `nil`,
  NaN: `NaN`,
  empty: `Empty`,
  emptyString: `Empty String`,
  emptyArray: `Empty Array`,
  validNumber: `Valid Number`,
  validDate: `Valid Date`,
  positive: `Positive`,
  negative: `Negative`,
  nonPositive: `Non-Positive`,
  nonNegative: `Non-Negative`,
  true: `True`,
  false: `False`,
  truthy: `Truthy`,
  falsy: `Falsy`,
})
