import { isNil, isEmpty } from 'ramda'
import {
  isNotArray,
  isArray,
  isBoolean,
  isNotBoolean,
  isNotDate,
  isEmptyArray,
  isNonEmptyArray,
  isNonEmptyString,
  isEmptyString,
  isDate,
  isFunction,
  isString,
  isNotString,
  isNotFunction,
  isNotNaN,
  isNaN,
  isNotNil,
  isNotEmpty,
  isNull,
  isNotNull,
  isNotNumber,
  isNumber,
  isUndefined,
  isNotUndefined,
  isValidDate,
  isNotValidDate,
  isNotValidNumber,
  isValidNumber,
  isPositive,
  isNegative,
  isObject,
  isNotObject,
  isPlainObject,
  isNotPlainObject,
} from 'ramda-adjunct'
import PREDICATES from '../../const/predicates'

export default {
  validateIsArray: [isArray, PREDICATES.Array],
  validateIsNotArray: [isNotArray, PREDICATES.Array, true],
  validateIsObject: [isObject, PREDICATES.Object],
  validateIsNotObject: [isNotObject, PREDICATES.Object, true],
  validateIsBoolean: [isBoolean, PREDICATES.Boolean],
  validateIsNotBoolean: [isNotBoolean, PREDICATES.Boolean, true],
  validateIsDate: [isDate, PREDICATES.Date],
  validateIsNotDate: [isNotDate, PREDICATES.Date, true],
  validateIsString: [isString, PREDICATES.Date],
  validateIsNotString: [isNotString, PREDICATES.Date, true],
  validateIsEmpty: [isEmpty, PREDICATES.empty],
  validateIsNotEmpty: [isNotEmpty, PREDICATES.empty, true],
  validateIsEmptyArray: [isEmptyArray, PREDICATES.emptyArray],
  validateIsNonEmptyArray: [isNonEmptyArray, PREDICATES.emptyArray, true],
  validateIsEmptyString: [isEmptyString, PREDICATES.emptyString],
  validateIsNonEmptyString: [isNonEmptyString, PREDICATES.emptyString, true],
  validateIsFunction: [isFunction, PREDICATES.Function],
  validateIsNotFunction: [isNotFunction, PREDICATES.Function, true],
  validateIsNaN: [isNaN, PREDICATES.NaN],
  validateIsNotNaN: [isNotNaN, PREDICATES.NaN, true],
  validateIsNil: [isNil, PREDICATES.Nil],
  validateIsNotNil: [isNotNil, PREDICATES.Nil, true],
  validateIsNull: [isNull, PREDICATES.Null],
  validateIsNotNull: [isNotNull, PREDICATES.Null, true],
  validateIsUndefined: [isUndefined, PREDICATES.Undefined],
  validateIsNotUndefined: [isNotUndefined, PREDICATES.Undefined, true],
  validateIsPlainObject: [isPlainObject, PREDICATES.plainObject],
  validateIsNotPlainObject: [isNotPlainObject, PREDICATES.plainObject, true],
  validateIsNumber: [isNumber, PREDICATES.Number],
  validateIsNotNumber: [isNotNumber, PREDICATES.Number, true],
  validateIsValidDate: [isValidDate, PREDICATES.validDate],
  validateIsNotValidDate: [isNotValidDate, PREDICATES.validDate, true],
  validateIsValidNumber: [isValidNumber, PREDICATES.validNumber],
  validateIsNotValidNumber: [isNotValidNumber, PREDICATES.validNumber, true],
  validateIsPositive: [isPositive, PREDICATES.positive],
  validateIsNegative: [isNegative, PREDICATES.negative],
}
