import { isNil, isEmpty } from 'ramda'
import {
  isNotArray,
  isArray,
  isBoolean,
  isNotBoolean,
  isNotDate,
  isEmptyArray,
  isNonEmptyArray,
  isNonEmptyString,
  isEmptyString,
  isDate,
  isFunction,
  isString,
  isNotString,
  isNotFunction,
  isNotNaN,
  isNaN,
  isNotNil,
  isNotEmpty,
  isNull,
  isNotNull,
  isNotNumber,
  isNumber,
  isUndefined,
  isNotUndefined,
  isValidDate,
  isNotValidDate,
  isNotValidNumber,
  isValidNumber,
  isPositive,
  isNegative,
  isObject,
  isNotObject,
  isPlainObject,
  isNotPlainObject,
} from 'ramda-adjunct'
import PREDICATES from '../../const/predicates'
import * as UIDS from '../../const/validatorUids'

export default {
  [UIDS.IS_ARRAY]: [`validateIsArray`, isArray, PREDICATES.Array],
  [UIDS.IS_NOT_ARRAY]: [
    `validateIsNotArray`,
    isNotArray,
    PREDICATES.Array,
    true,
  ],
  [UIDS.IS_OBJECT]: [`validateIsObject`, isObject, PREDICATES.Object],
  [UIDS.IS_NOT_OBJECT]: [
    `validateIsNotObject`,
    isNotObject,
    PREDICATES.Object,
    true,
  ],
  [UIDS.IS_BOOLEAN]: [`validateIsBoolean`, isBoolean, PREDICATES.Boolean],
  [UIDS.IS_NOT_BOOLEAN]: [
    `validateIsNotBoolean`,
    isNotBoolean,
    PREDICATES.Boolean,
    true,
  ],
  [UIDS.IS_DATE]: [`validateIsDate`, isDate, PREDICATES.Date],
  [UIDS.IS_NOT_DATE]: [`validateIsNotDate`, isNotDate, PREDICATES.Date, true],
  [UIDS.IS_STRING]: [`validateIsString`, isString, PREDICATES.Date],
  [UIDS.IS_NOT_STRING]: [
    `validateIsNotString`,
    isNotString,
    PREDICATES.Date,
    true,
  ],
  [UIDS.IS_EMPTY]: [`validateIsEmpty`, isEmpty, PREDICATES.empty],
  [UIDS.IS_NOT_EMPTY]: [
    `validateIsNotEmpty`,
    isNotEmpty,
    PREDICATES.empty,
    true,
  ],
  [UIDS.IS_EMPTY_ARRAY]: [
    `validateIsEmptyArray`,
    isEmptyArray,
    PREDICATES.emptyArray,
  ],
  [UIDS.IS_NON_EMPTY_ARRAY]: [
    `validateIsNonEmptyArray`,
    isNonEmptyArray,
    PREDICATES.emptyArray,
    true,
  ],
  [UIDS.IS_EMPTY_STRING]: [
    `validateIsEmptyString`,
    isEmptyString,
    PREDICATES.emptyString,
  ],
  [UIDS.IS_NON_EMPTY_STRING]: [
    `validateIsNonEmptyString`,
    isNonEmptyString,
    PREDICATES.emptyString,
    true,
  ],
  [UIDS.IS_FUNCTION]: [`validateIsFunction`, isFunction, PREDICATES.Function],
  [UIDS.IS_NOT_FUNCTION]: [
    `validateIsNotFunction`,
    isNotFunction,
    PREDICATES.Function,
    true,
  ],
  [UIDS.IS_NAN]: [`validateIsNaN`, isNaN, PREDICATES.NaN],
  [UIDS.IS_NOT_NAN]: [`validateIsNotNaN`, isNotNaN, PREDICATES.NaN, true],
  [UIDS.IS_NIL]: [`validateIsNil`, isNil, PREDICATES.Nil],
  [UIDS.IS_NOT_NIL]: [`validateIsNotNil`, isNotNil, PREDICATES.Nil, true],
  [UIDS.IS_NULL]: [`validateIsNull`, isNull, PREDICATES.Null],
  [UIDS.IS_NOT_NULL]: [`validateIsNotNull`, isNotNull, PREDICATES.Null, true],
  [UIDS.IS_UNDEFINED]: [
    `validateIsUndefined`,
    isUndefined,
    PREDICATES.Undefined,
  ],
  [UIDS.IS_NOT_UNDEFINED]: [
    `validateIsNotUndefined`,
    isNotUndefined,
    PREDICATES.Undefined,
    true,
  ],
  [UIDS.IS_PLAIN_OBJECT]: [
    `validateIsPlainObject`,
    isPlainObject,
    PREDICATES.plainObject,
  ],
  [UIDS.IS_NOT_PLAIN_OBJECT]: [
    `validateIsNotPlainObject`,
    isNotPlainObject,
    PREDICATES.plainObject,
    true,
  ],
  [UIDS.IS_NUMBER]: [`validateIsNumber`, isNumber, PREDICATES.Number],
  [UIDS.IS_NOT_NUMBER]: [
    `validateIsNotNumber`,
    isNotNumber,
    PREDICATES.Number,
    true,
  ],
  [UIDS.IS_VALID_DATE]: [
    `validateIsValidDate`,
    isValidDate,
    PREDICATES.validDate,
  ],
  [UIDS.IS_NOT_VALID_DATE]: [
    `validateIsNotValidDate`,
    isNotValidDate,
    PREDICATES.validDate,
    true,
  ],
  [UIDS.IS_VALID_NUMBER]: [
    `validateIsValidNumber`,
    isValidNumber,
    PREDICATES.validNumber,
  ],
  [UIDS.IS_NOT_VALID_NUMBER]: [
    `validateIsNotValidNumber`,
    isNotValidNumber,
    PREDICATES.validNumber,
    true,
  ],
  [UIDS.IS_POSITIVE]: [`validateIsPositive`, isPositive, PREDICATES.positive],
  [UIDS.IS_NEGATIVE]: [`validateIsNegative`, isNegative, PREDICATES.negative],
}
